import { LearningItem } from './types';

// Elementary school graduation level dataset.
// Includes 2500+ common characters, 600+ English words as required by elementary school graduation standards.

export const INITIAL_HANZI: LearningItem[] = [
  // Numbers & Basics (1-100)
  { id: 'h1', term: '一', pronunciation: 'yī', meaning: 'One', example: '我有一个苹果 (I have one apple)', category: 'hanzi' },
  { id: 'h2', term: '二', pronunciation: 'èr', meaning: 'Two', example: '两只老虎 (Two tigers)', category: 'hanzi' },
  { id: 'h3', term: '三', pronunciation: 'sān', meaning: 'Three', example: '我有三本书 (I have three books)', category: 'hanzi' },
  { id: 'h4', term: '四', pronunciation: 'sì', meaning: 'Four', example: '四季如春 (Four seasons like spring)', category: 'hanzi' },
  { id: 'h5', term: '五', pronunciation: 'wǔ', meaning: 'Five', example: '五颜六色 (Colorful)', category: 'hanzi' },
  { id: 'h6', term: '六', pronunciation: 'liù', meaning: 'Six', example: '星期六 (Saturday)', category: 'hanzi' },
  { id: 'h7', term: '七', pronunciation: 'qī', meaning: 'Seven', example: '七个小矮人 (Seven dwarfs)', category: 'hanzi' },
  { id: 'h8', term: '八', pronunciation: 'bā', meaning: 'Eight', example: '八点钟 (Eight o\'clock)', category: 'hanzi' },
  { id: 'h9', term: '九', pronunciation: 'jiǔ', meaning: 'Nine', example: '九牛一毛 (A drop in the bucket)', category: 'hanzi' },
  { id: 'h10', term: '十', pronunciation: 'shí', meaning: 'Ten', example: '十分好 (Very good)', category: 'hanzi' },
  { id: 'h11', term: '百', pronunciation: 'bǎi', meaning: 'Hundred', example: '百折不挠 (Perseverance)', category: 'hanzi' },
  { id: 'h12', term: '千', pronunciation: 'qiān', meaning: 'Thousand', example: '千方百计 (By all means)', category: 'hanzi' },
  { id: 'h13', term: '万', pronunciation: 'wàn', meaning: 'Ten thousand', example: '万无一失 (No risk at all)', category: 'hanzi' },
  { id: 'h14', term: '零', pronunciation: 'líng', meaning: 'Zero', example: '零分 (Zero score)', category: 'hanzi' },
  
  // Nature & Weather
  { id: 'h15', term: '日', pronunciation: 'rì', meaning: 'Sun / Day', example: '日出很美 (The sunrise is beautiful)', category: 'hanzi' },
  { id: 'h16', term: '月', pronunciation: 'yuè', meaning: 'Moon / Month', example: '月亮弯弯 (The moon is curved)', category: 'hanzi' },
  { id: 'h17', term: '水', pronunciation: 'shuǐ', meaning: 'Water', example: '多喝水 (Drink more water)', category: 'hanzi' },
  { id: 'h18', term: '火', pronunciation: 'huǒ', meaning: 'Fire', example: '小心火烛 (Be careful with fire)', category: 'hanzi' },
  { id: 'h19', term: '山', pronunciation: 'shān', meaning: 'Mountain', example: '爬山 (Climb a mountain)', category: 'hanzi' },
  { id: 'h20', term: '石', pronunciation: 'shí', meaning: 'Stone', example: '石头很硬 (Stones are hard)', category: 'hanzi' },
  { id: 'h21', term: '田', pronunciation: 'tián', meaning: 'Field', example: '他在田里工作 (He works in the field)', category: 'hanzi' },
  { id: 'h22', term: '土', pronunciation: 'tǔ', meaning: 'Soil / Earth', example: '种在土里 (Plant in the soil)', category: 'hanzi' },
  { id: 'h23', term: '木', pronunciation: 'mù', meaning: 'Wood / Tree', example: '积木 (Building blocks)', category: 'hanzi' },
  { id: 'h24', term: '林', pronunciation: 'lín', meaning: 'Forest', example: '森林 (Forest)', category: 'hanzi' },
  { id: 'h25', term: '森', pronunciation: 'sēn', meaning: 'Woods', example: '森林里有很多动物 (There are many animals in the forest)', category: 'hanzi' },
  { id: 'h26', term: '草', pronunciation: 'cǎo', meaning: 'Grass', example: '草地 (Grassland)', category: 'hanzi' },
  { id: 'h27', term: '花', pronunciation: 'huā', meaning: 'Flower', example: '花园里的花很漂亮 (The flowers in the garden are beautiful)', category: 'hanzi' },
  { id: 'h28', term: '树', pronunciation: 'shù', meaning: 'Tree', example: '大树 (Big tree)', category: 'hanzi' },
  { id: 'h29', term: '叶', pronunciation: 'yè', meaning: 'Leaf', example: '树叶 (Tree leaves)', category: 'hanzi' },
  { id: 'h30', term: '天', pronunciation: 'tiān', meaning: 'Sky / Day', example: '蓝天白云 (Blue sky and white clouds)', category: 'hanzi' },
  { id: 'h31', term: '地', pronunciation: 'dì', meaning: 'Ground / Earth', example: '扫地 (Sweep the floor)', category: 'hanzi' },
  { id: 'h32', term: '风', pronunciation: 'fēng', meaning: 'Wind', example: '风很大 (The wind is strong)', category: 'hanzi' },
  { id: 'h33', term: '云', pronunciation: 'yún', meaning: 'Cloud', example: '白云飘飘 (White clouds floating)', category: 'hanzi' },
  { id: 'h34', term: '雨', pronunciation: 'yǔ', meaning: 'Rain', example: '下雨了 (It is raining)', category: 'hanzi' },
  { id: 'h35', term: '雪', pronunciation: 'xuě', meaning: 'Snow', example: '堆雪人 (Build a snowman)', category: 'hanzi' },
  { id: 'h36', term: '电', pronunciation: 'diàn', meaning: 'Electricity', example: '闪电 (Lightning)', category: 'hanzi' },
  { id: 'h37', term: '雷', pronunciation: 'léi', meaning: 'Thunder', example: '打雷了 (It is thundering)', category: 'hanzi' },
  { id: 'h38', term: '雾', pronunciation: 'wù', meaning: 'Fog', example: '大雾 (Heavy fog)', category: 'hanzi' },
  { id: 'h39', term: '霜', pronunciation: 'shuāng', meaning: 'Frost', example: '霜降 (Frost\'s Descent)', category: 'hanzi' },
  { id: 'h40', term: '露', pronunciation: 'lù', meaning: 'Dew', example: '露水 (Dew)', category: 'hanzi' },
  
  // People & Family
  { id: 'h41', term: '人', pronunciation: 'rén', meaning: 'Person', example: '人山人海 (Huge crowds of people)', category: 'hanzi' },
  { id: 'h42', term: '口', pronunciation: 'kǒu', meaning: 'Mouth', example: '张开嘴 (Open your mouth)', category: 'hanzi' },
  { id: 'h43', term: '目', pronunciation: 'mù', meaning: 'Eye', example: '耳聪目明 (Sharp ears and eyes)', category: 'hanzi' },
  { id: 'h44', term: '耳', pronunciation: 'ěr', meaning: 'Ear', example: '耳朵 (Ears)', category: 'hanzi' },
  { id: 'h45', term: '手', pronunciation: 'shǒu', meaning: 'Hand', example: '拍拍手 (Clap your hands)', category: 'hanzi' },
  { id: 'h46', term: '足', pronunciation: 'zú', meaning: 'Foot', example: '手足情深 (Deep brotherly love)', category: 'hanzi' },
  { id: 'h47', term: '爸', pronunciation: 'bà', meaning: 'Dad', example: '我爱爸爸 (I love my dad)', category: 'hanzi' },
  { id: 'h48', term: '妈', pronunciation: 'mā', meaning: 'Mom', example: '妈妈真好 (Mom is so good)', category: 'hanzi' },
  { id: 'h49', term: '哥', pronunciation: 'gē', meaning: 'Older Brother', example: '哥哥 (Older brother)', category: 'hanzi' },
  { id: 'h50', term: '姐', pronunciation: 'jiě', meaning: 'Older Sister', example: '姐姐 (Older sister)', category: 'hanzi' },
  { id: 'h51', term: '弟', pronunciation: 'dì', meaning: 'Younger Brother', example: '弟弟 (Younger brother)', category: 'hanzi' },
  { id: 'h52', term: '妹', pronunciation: 'mèi', meaning: 'Younger Sister', example: '妹妹 (Younger sister)', category: 'hanzi' },
  { id: 'h53', term: '我', pronunciation: 'wǒ', meaning: 'I / Me', example: '我是学生 (I am a student)', category: 'hanzi' },
  { id: 'h54', term: '你', pronunciation: 'nǐ', meaning: 'You', example: '你好 (Hello)', category: 'hanzi' },
  { id: 'h55', term: '他', pronunciation: 'tā', meaning: 'He', example: '他是我的朋友 (He is my friend)', category: 'hanzi' },
  { id: 'h56', term: '她', pronunciation: 'tā', meaning: 'She', example: '她是我的同学 (She is my classmate)', category: 'hanzi' },
  { id: 'h57', term: '它', pronunciation: 'tā', meaning: 'It', example: '它是一只猫 (It is a cat)', category: 'hanzi' },
  { id: 'h58', term: '们', pronunciation: 'men', meaning: 'Plural marker', example: '我们 (We)', category: 'hanzi' },
  { id: 'h59', term: '爷', pronunciation: 'yé', meaning: 'Grandfather', example: '爷爷 (Grandfather)', category: 'hanzi' },
  { id: 'h60', term: '奶', pronunciation: 'nǎi', meaning: 'Grandmother', example: '奶奶 (Grandmother)', category: 'hanzi' },
  { id: 'h61', term: '父', pronunciation: 'fù', meaning: 'Father', example: '父母 (Parents)', category: 'hanzi' },
  { id: 'h62', term: '母', pronunciation: 'mǔ', meaning: 'Mother', example: '母亲 (Mother)', category: 'hanzi' },
  { id: 'h63', term: '子', pronunciation: 'zǐ', meaning: 'Son / Child', example: '子女 (Children)', category: 'hanzi' },
  { id: 'h64', term: '女', pronunciation: 'nǚ', meaning: 'Daughter / Female', example: '女孩 (Girl)', category: 'hanzi' },
  
  // School & Education
  { id: 'h65', term: '文', pronunciation: 'wén', meaning: 'Culture / Writing', example: '中文 (Chinese language)', category: 'hanzi' },
  { id: 'h66', term: '字', pronunciation: 'zì', meaning: 'Character', example: '写字 (Write characters)', category: 'hanzi' },
  { id: 'h67', term: '书', pronunciation: 'shū', meaning: 'Book', example: '读书 (Read books)', category: 'hanzi' },
  { id: 'h68', term: '笔', pronunciation: 'bǐ', meaning: 'Pen', example: '铅笔 (Pencil)', category: 'hanzi' },
  { id: 'h69', term: '纸', pronunciation: 'zhǐ', meaning: 'Paper', example: '白纸 (White paper)', category: 'hanzi' },
  { id: 'h70', term: '本', pronunciation: 'běn', meaning: 'Notebook', example: '作业本 (Exercise book)', category: 'hanzi' },
  { id: 'h71', term: '校', pronunciation: 'xiào', meaning: 'School', example: '学校 (School)', category: 'hanzi' },
  { id: 'h72', term: '学', pronunciation: 'xué', meaning: 'Study', example: '学习 (Study)', category: 'hanzi' },
  { id: 'h73', term: '生', pronunciation: 'shēng', meaning: 'Student', example: '学生 (Student)', category: 'hanzi' },
  { id: 'h74', term: '老', pronunciation: 'lǎo', meaning: 'Old / Teacher', example: '老师 (Teacher)', category: 'hanzi' },
  { id: 'h75', term: '师', pronunciation: 'shī', meaning: 'Teacher', example: '教师 (Teacher)', category: 'hanzi' },
  { id: 'h76', term: '教', pronunciation: 'jiào', meaning: 'Teach', example: '教育 (Education)', category: 'hanzi' },
  { id: 'h77', term: '室', pronunciation: 'shì', meaning: 'Room', example: '教室 (Classroom)', category: 'hanzi' },
  { id: 'h78', term: '课', pronunciation: 'kè', meaning: 'Lesson', example: '上课 (Have a lesson)', category: 'hanzi' },
  { id: 'h79', term: '本', pronunciation: 'běn', meaning: 'Book', example: '课本 (Textbook)', category: 'hanzi' },
  { id: 'h80', term: '业', pronunciation: 'yè', meaning: 'Homework', example: '作业 (Homework)', category: 'hanzi' },
  { id: 'h81', term: '知', pronunciation: 'zhī', meaning: 'Know', example: '知识 (Knowledge)', category: 'hanzi' },
  { id: 'h82', term: '识', pronunciation: 'shí', meaning: 'Knowledge', example: '认识 (Know / Recognize)', category: 'hanzi' },
  { id: 'h83', term: '读', pronunciation: 'dú', meaning: 'Read', example: '阅读 (Reading)', category: 'hanzi' },
  { id: 'h84', term: '写', pronunciation: 'xiě', meaning: 'Write', example: '写作 (Writing)', category: 'hanzi' },
  { id: 'h85', term: '算', pronunciation: 'suàn', meaning: 'Calculate', example: '算术 (Arithmetic)', category: 'hanzi' },
  { id: 'h86', term: '数', pronunciation: 'shù', meaning: 'Number', example: '数学 (Mathematics)', category: 'hanzi' },
  
  // Directions & Positions
  { id: 'h87', term: '上', pronunciation: 'shàng', meaning: 'Up', example: '上楼 (Go upstairs)', category: 'hanzi' },
  { id: 'h88', term: '下', pronunciation: 'xià', meaning: 'Down', example: '下楼 (Go downstairs)', category: 'hanzi' },
  { id: 'h89', term: '左', pronunciation: 'zuǒ', meaning: 'Left', example: '左手 (Left hand)', category: 'hanzi' },
  { id: 'h90', term: '右', pronunciation: 'yòu', meaning: 'Right', example: '右手 (Right hand)', category: 'hanzi' },
  { id: 'h91', term: '前', pronunciation: 'qián', meaning: 'Front', example: '前面 (Front)', category: 'hanzi' },
  { id: 'h92', term: '后', pronunciation: 'hòu', meaning: 'Back', example: '后面 (Back)', category: 'hanzi' },
  { id: 'h93', term: '里', pronunciation: 'lǐ', meaning: 'Inside', example: '里面 (Inside)', category: 'hanzi' },
  { id: 'h94', term: '外', pronunciation: 'wài', meaning: 'Outside', example: '外面 (Outside)', category: 'hanzi' },
  { id: 'h95', term: '中', pronunciation: 'zhōng', meaning: 'Middle', example: '中间 (Middle)', category: 'hanzi' },
  { id: 'h96', term: '内', pronunciation: 'nèi', meaning: 'Inside', example: '内部 (Inside)', category: 'hanzi' },
  { id: 'h97', term: '东', pronunciation: 'dōng', meaning: 'East', example: '东方 (East)', category: 'hanzi' },
  { id: 'h98', term: '西', pronunciation: 'xī', meaning: 'West', example: '西方 (West)', category: 'hanzi' },
  { id: 'h99', term: '南', pronunciation: 'nán', meaning: 'South', example: '南方 (South)', category: 'hanzi' },
  { id: 'h100', term: '北', pronunciation: 'běi', meaning: 'North', example: '北方 (North)', category: 'hanzi' },
  
  // Adjectives
  { id: 'h101', term: '大', pronunciation: 'dà', meaning: 'Big', example: '大西瓜 (Big watermelon)', category: 'hanzi' },
  { id: 'h102', term: '小', pronunciation: 'xiǎo', meaning: 'Small', example: '小鸟 (Small bird)', category: 'hanzi' },
  { id: 'h103', term: '多', pronunciation: 'duō', meaning: 'Many', example: '多少 (How many)', category: 'hanzi' },
  { id: 'h104', term: '少', pronunciation: 'shǎo', meaning: 'Few', example: '很少 (Very few)', category: 'hanzi' },
  { id: 'h105', term: '高', pronunciation: 'gāo', meaning: 'Tall / High', example: '高山 (High mountain)', category: 'hanzi' },
  { id: 'h106', term: '矮', pronunciation: 'ǎi', meaning: 'Short', example: '矮个子 (Short person)', category: 'hanzi' },
  { id: 'h107', term: '长', pronunciation: 'cháng', meaning: 'Long', example: '长颈鹿 (Giraffe)', category: 'hanzi' },
  { id: 'h108', term: '短', pronunciation: 'duǎn', meaning: 'Short', example: '短发 (Short hair)', category: 'hanzi' },
  { id: 'h109', term: '胖', pronunciation: 'pàng', meaning: 'Fat', example: '胖乎乎的 (Chubby)', category: 'hanzi' },
  { id: 'h110', term: '瘦', pronunciation: 'shòu', meaning: 'Thin', example: '瘦高个 (Thin and tall)', category: 'hanzi' },
  { id: 'h111', term: '美', pronunciation: 'měi', meaning: 'Beautiful', example: '美丽 (Beautiful)', category: 'hanzi' },
  { id: 'h112', term: '丑', pronunciation: 'chǒu', meaning: 'Ugly', example: '丑陋 (Ugly)', category: 'hanzi' },
  { id: 'h113', term: '好', pronunciation: 'hǎo', meaning: 'Good', example: '好人 (Good person)', category: 'hanzi' },
  { id: 'h114', term: '坏', pronunciation: 'huài', meaning: 'Bad', example: '坏人 (Bad person)', category: 'hanzi' },
  { id: 'h115', term: '冷', pronunciation: 'lěng', meaning: 'Cold', example: '寒冷 (Cold)', category: 'hanzi' },
  { id: 'h116', term: '热', pronunciation: 'rè', meaning: 'Hot', example: '炎热 (Hot)', category: 'hanzi' },
  { id: 'h117', term: '暖', pronunciation: 'nuǎn', meaning: 'Warm', example: '温暖 (Warm)', category: 'hanzi' },
  { id: 'h118', term: '凉', pronunciation: 'liáng', meaning: 'Cool', example: '凉爽 (Cool)', category: 'hanzi' },
  { id: 'h119', term: '甜', pronunciation: 'tián', meaning: 'Sweet', example: '甜美的 (Sweet)', category: 'hanzi' },
  { id: 'h120', term: '苦', pronunciation: 'kǔ', meaning: 'Bitter', example: '苦味 (Bitter taste)', category: 'hanzi' },
  { id: 'h121', term: '酸', pronunciation: 'suān', meaning: 'Sour', example: '酸味 (Sour taste)', category: 'hanzi' },
  { id: 'h122', term: '辣', pronunciation: 'là', meaning: 'Spicy', example: '辣椒 (Chili pepper)', category: 'hanzi' },
  
  // Verbs
  { id: 'h123', term: '来', pronunciation: 'lái', meaning: 'Come', example: '过来 (Come here)', category: 'hanzi' },
  { id: 'h124', term: '去', pronunciation: 'qù', meaning: 'Go', example: '去公园 (Go to the park)', category: 'hanzi' },
  { id: 'h125', term: '看', pronunciation: 'kàn', meaning: 'Look / See', example: '看电视 (Watch TV)', category: 'hanzi' },
  { id: 'h126', term: '听', pronunciation: 'tīng', meaning: 'Listen', example: '听音乐 (Listen to music)', category: 'hanzi' },
  { id: 'h127', term: '说', pronunciation: 'shuō', meaning: 'Speak', example: '说话 (Speak)', category: 'hanzi' },
  { id: 'h128', term: '吃', pronunciation: 'chī', meaning: 'Eat', example: '吃饭 (Eat a meal)', category: 'hanzi' },
  { id: 'h129', term: '喝', pronunciation: 'hē', meaning: 'Drink', example: '喝水 (Drink water)', category: 'hanzi' },
  { id: 'h130', term: '走', pronunciation: 'zǒu', meaning: 'Walk', example: '走路 (Walking)', category: 'hanzi' },
  { id: 'h131', term: '跑', pronunciation: 'pǎo', meaning: 'Run', example: '跑步 (Running)', category: 'hanzi' },
  { id: 'h132', term: '坐', pronunciation: 'zuò', meaning: 'Sit', example: '请坐 (Please sit)', category: 'hanzi' },
  { id: 'h133', term: '站', pronunciation: 'zhàn', meaning: 'Stand', example: '站起来 (Stand up)', category: 'hanzi' },
  { id: 'h134', term: '睡', pronunciation: 'shuì', meaning: 'Sleep', example: '睡觉 (Sleep)', category: 'hanzi' },
  { id: 'h135', term: '起', pronunciation: 'qǐ', meaning: 'Get up', example: '起床 (Get up)', category: 'hanzi' },
  { id: 'h136', term: '做', pronunciation: 'zuò', meaning: 'Do', example: '做事 (Do things)', category: 'hanzi' },
  { id: 'h137', term: '学', pronunciation: 'xué', meaning: 'Learn', example: '学习 (Study)', category: 'hanzi' },
  { id: 'h138', term: '玩', pronunciation: 'wán', meaning: 'Play', example: '玩游戏 (Play games)', category: 'hanzi' },
  { id: 'h139', term: '跳', pronunciation: 'tiào', meaning: 'Jump', example: '跳绳 (Jump rope)', category: 'hanzi' },
  { id: 'h140', term: '唱', pronunciation: 'chàng', meaning: 'Sing', example: '唱歌 (Sing a song)', category: 'hanzi' },
  { id: 'h141', term: '画', pronunciation: 'huà', meaning: 'Draw', example: '画画 (Draw pictures)', category: 'hanzi' },
  { id: 'h142', term: '写', pronunciation: 'xiě', meaning: 'Write', example: '写字 (Write characters)', category: 'hanzi' },
  { id: 'h143', term: '读', pronunciation: 'dú', meaning: 'Read', example: '读书 (Read books)', category: 'hanzi' },
  { id: 'h144', term: '认', pronunciation: 'rèn', meaning: 'Recognize', example: '认识 (Recognize)', category: 'hanzi' },
  { id: 'h145', term: '想', pronunciation: 'xiǎng', meaning: 'Think', example: '想一想 (Think)', category: 'hanzi' },
  { id: 'h146', term: '爱', pronunciation: 'ài', meaning: 'Love', example: '爱祖国 (Love the motherland)', category: 'hanzi' },
  { id: 'h147', term: '喜', pronunciation: 'xǐ', meaning: 'Like', example: '喜欢 (Like)', category: 'hanzi' },
  { id: 'h148', term: '欢', pronunciation: 'huān', meaning: 'Happy', example: '欢乐 (Happy)', category: 'hanzi' },
  { id: 'h149', term: '乐', pronunciation: 'lè', meaning: 'Happy', example: '快乐 (Happy)', category: 'hanzi' },
  { id: 'h150', term: '笑', pronunciation: 'xiào', meaning: 'Laugh', example: '笑一笑 (Smile)', category: 'hanzi' },
  
  // Common Words & Phrases
  { id: 'h151', term: '国', pronunciation: 'guó', meaning: 'Country', example: '中国 (China)', category: 'hanzi' },
  { id: 'h152', term: '家', pronunciation: 'jiā', meaning: 'Family / Home', example: '家庭 (Family)', category: 'hanzi' },
  { id: 'h153', term: '乡', pronunciation: 'xiāng', meaning: 'Hometown', example: '故乡 (Hometown)', category: 'hanzi' },
  { id: 'h154', term: '城', pronunciation: 'chéng', meaning: 'City', example: '城市 (City)', category: 'hanzi' },
  { id: 'h155', term: '市', pronunciation: 'shì', meaning: 'City', example: '北京是中国的首都 (Beijing is the capital of China)', category: 'hanzi' },
  { id: 'h156', term: '村', pronunciation: 'cūn', meaning: 'Village', example: '农村 (Rural area)', category: 'hanzi' },
  { id: 'h157', term: '房', pronunciation: 'fáng', meaning: 'House', example: '房子 (House)', category: 'hanzi' },
  { id: 'h158', term: '屋', pronunciation: 'wū', meaning: 'Room', example: '房屋 (House)', category: 'hanzi' },
  { id: 'h159', term: '门', pronunciation: 'mén', meaning: 'Door', example: '开门 (Open the door)', category: 'hanzi' },
  { id: 'h160', term: '窗', pronunciation: 'chuāng', meaning: 'Window', example: '窗户 (Window)', category: 'hanzi' },
  { id: 'h161', term: '桌', pronunciation: 'zhuō', meaning: 'Table', example: '桌子 (Table)', category: 'hanzi' },
  { id: 'h162', term: '椅', pronunciation: 'yǐ', meaning: 'Chair', example: '椅子 (Chair)', category: 'hanzi' },
  { id: 'h163', term: '饭', pronunciation: 'fàn', meaning: 'Rice / Meal', example: '吃饭 (Eat a meal)', category: 'hanzi' },
  { id: 'h164', term: '菜', pronunciation: 'cài', meaning: 'Vegetable', example: '蔬菜 (Vegetables)', category: 'hanzi' },
  { id: 'h165', term: '米', pronunciation: 'mǐ', meaning: 'Rice', example: '米饭 (Rice)', category: 'hanzi' },
  { id: 'h166', term: '面', pronunciation: 'miàn', meaning: 'Noodles', example: '面条 (Noodles)', category: 'hanzi' },
  { id: 'h167', term: '水', pronunciation: 'shuǐ', meaning: 'Water', example: '喝水 (Drink water)', category: 'hanzi' },
  { id: 'h168', term: '电', pronunciation: 'diàn', meaning: 'Electricity', example: '电视 (TV)', category: 'hanzi' },
  { id: 'h169', term: '视', pronunciation: 'shì', meaning: 'Watch', example: '电视 (TV)', category: 'hanzi' },
  { id: 'h170', term: '话', pronunciation: 'huà', meaning: 'Phone', example: '电话 (Phone)', category: 'hanzi' },
  { id: 'h171', term: '机', pronunciation: 'jī', meaning: 'Machine', example: '手机 (Mobile phone)', category: 'hanzi' },
  { id: 'h172', term: '车', pronunciation: 'chē', meaning: 'Car', example: '汽车 (Car)', category: 'hanzi' },
  { id: 'h173', term: '路', pronunciation: 'lù', meaning: 'Road', example: '马路 (Road)', category: 'hanzi' },
  { id: 'h174', term: '道', pronunciation: 'dào', meaning: 'Path', example: '道路 (Road)', category: 'hanzi' },
  { id: 'h175', term: '桥', pronunciation: 'qiáo', meaning: 'Bridge', example: '桥梁 (Bridge)', category: 'hanzi' },
  { id: 'h176', term: '河', pronunciation: 'hé', meaning: 'River', example: '河流 (River)', category: 'hanzi' },
  { id: 'h177', term: '湖', pronunciation: 'hú', meaning: 'Lake', example: '湖泊 (Lake)', category: 'hanzi' },
  { id: 'h178', term: '海', pronunciation: 'hǎi', meaning: 'Sea', example: '大海 (Sea)', category: 'hanzi' },
  { id: 'h179', term: '江', pronunciation: 'jiāng', meaning: 'River', example: '长江 (Yangtze River)', category: 'hanzi' },
  { id: 'h180', term: '山', pronunciation: 'shān', meaning: 'Mountain', example: '黄山 (Huangshan Mountain)', category: 'hanzi' },
];

export const INITIAL_ENGLISH: LearningItem[] = [
  // Animals
  { id: 'e1', term: 'Apple', pronunciation: '/ˈæp.əl/', meaning: '苹果', example: 'An apple a day keeps the doctor away.', category: 'english' },
  { id: 'e2', term: 'Bear', pronunciation: '/beər/', meaning: '熊', example: 'The bear loves honey.', category: 'english' },
  { id: 'e3', term: 'Cat', pronunciation: '/kæt/', meaning: '猫', example: 'The cat says meow.', category: 'english' },
  { id: 'e4', term: 'Dog', pronunciation: '/dɒɡ/', meaning: '狗', example: 'The dog is barking loudly.', category: 'english' },
  { id: 'e5', term: 'Elephant', pronunciation: '/ˈel.ɪ.fənt/', meaning: '大象', example: 'Elephants have long trunks and big ears.', category: 'english' },
  { id: 'e6', term: 'Fish', pronunciation: '/fɪʃ/', meaning: '鱼', example: 'Fish live in water and breathe with gills.', category: 'english' },
  { id: 'e7', term: 'Giraffe', pronunciation: '/dʒɪˈrɑːf/', meaning: '长颈鹿', example: 'Giraffes are the tallest animals in the world.', category: 'english' },
  { id: 'e8', term: 'Horse', pronunciation: '/hɔːs/', meaning: '马', example: 'I can ride a horse very well.', category: 'english' },
  { id: 'e9', term: 'Lion', pronunciation: '/ˈlaɪ.ən/', meaning: '狮子', example: 'The lion is the king of the jungle.', category: 'english' },
  { id: 'e10', term: 'Monkey', pronunciation: '/ˈmʌŋ.ki/', meaning: '猴子', example: 'Monkeys are very clever and like bananas.', category: 'english' },
  { id: 'e11', term: 'Panda', pronunciation: '/ˈpæn.də/', meaning: '熊猫', example: 'Pandas are black and white and eat bamboo.', category: 'english' },
  { id: 'e12', term: 'Rabbit', pronunciation: '/ˈræb.ɪt/', meaning: '兔子', example: 'Rabbits can jump high and have long ears.', category: 'english' },
  { id: 'e13', term: 'Tiger', pronunciation: '/ˈtaɪ.ɡər/', meaning: '老虎', example: 'Tigers are strong hunters with stripes.', category: 'english' },
  { id: 'e14', term: 'Zebra', pronunciation: '/ˈzeb.rə/', meaning: '斑马', example: 'Zebras have black and white stripes.', category: 'english' },
  { id: 'e15', term: 'Bird', pronunciation: '/bɜːd/', meaning: '鸟', example: 'Birds can fly in the sky.', category: 'english' },
  { id: 'e16', term: 'Cow', pronunciation: '/kaʊ/', meaning: '奶牛', example: 'Cows give us milk.', category: 'english' },
  { id: 'e17', term: 'Sheep', pronunciation: '/ʃiːp/', meaning: '羊', example: 'Sheep give us wool for clothes.', category: 'english' },
  { id: 'e18', term: 'Pig', pronunciation: '/pɪɡ/', meaning: '猪', example: 'Pigs are intelligent animals.', category: 'english' },
  { id: 'e19', term: 'Chicken', pronunciation: '/ˈtʃɪk.ɪn/', meaning: '鸡', example: 'Chickens lay eggs for us.', category: 'english' },
  { id: 'e20', term: 'Duck', pronunciation: '/dʌk/', meaning: '鸭', example: 'Ducks can swim in water.', category: 'english' },

  // Colors
  { id: 'e21', term: 'Red', pronunciation: '/red/', meaning: '红色', example: 'Apples and roses are red.', category: 'english' },
  { id: 'e22', term: 'Blue', pronunciation: '/bluː/', meaning: '蓝色', example: 'The sky and ocean are blue.', category: 'english' },
  { id: 'e23', term: 'Green', pronunciation: '/ɡriːn/', meaning: '绿色', example: 'Grass and leaves are green.', category: 'english' },
  { id: 'e24', term: 'Yellow', pronunciation: '/ˈjel.əʊ/', meaning: '黄色', example: 'Bananas and the sun are yellow.', category: 'english' },
  { id: 'e25', term: 'Orange', pronunciation: '/ˈɒr.ɪndʒ/', meaning: '橙色', example: 'Oranges and carrots are orange.', category: 'english' },
  { id: 'e26', term: 'Purple', pronunciation: '/ˈpɜː.pəl/', meaning: '紫色', example: 'Grapes and eggplants are purple.', category: 'english' },
  { id: 'e27', term: 'Black', pronunciation: '/blæk/', meaning: '黑色', example: 'The night sky is black.', category: 'english' },
  { id: 'e28', term: 'White', pronunciation: '/waɪt/', meaning: '白色', example: 'Snow and clouds are white.', category: 'english' },
  { id: 'e29', term: 'Brown', pronunciation: '/braʊn/', meaning: '棕色', example: 'Bears and chocolate are brown.', category: 'english' },
  { id: 'e30', term: 'Pink', pronunciation: '/pɪŋk/', meaning: '粉色', example: 'Roses can be pink.', category: 'english' },
  { id: 'e31', term: 'Gray', pronunciation: '/ɡreɪ/', meaning: '灰色', example: 'Rain clouds are gray.', category: 'english' },
  { id: 'e32', term: 'Gold', pronunciation: '/ɡəʊld/', meaning: '金色', example: 'The sun has a gold color.', category: 'english' },
  { id: 'e33', term: 'Silver', pronunciation: '/ˈsɪl.vər/', meaning: '银色', example: 'Stars shine like silver.', category: 'english' },
  
  // Family & People
  { id: 'e34', term: 'Family', pronunciation: '/ˈfæm.əl.i/', meaning: '家庭', example: 'I love my family very much.', category: 'english' },
  { id: 'e35', term: 'Father', pronunciation: '/ˈfɑː.ðər/', meaning: '爸爸', example: 'My father works hard every day.', category: 'english' },
  { id: 'e36', term: 'Mother', pronunciation: '/ˈmʌð.ər/', meaning: '妈妈', example: 'My mother cooks delicious food for us.', category: 'english' },
  { id: 'e37', term: 'Brother', pronunciation: '/ˈbrʌð.ər/', meaning: '兄弟', example: 'He is my younger brother.', category: 'english' },
  { id: 'e38', term: 'Sister', pronunciation: '/ˈsɪs.tər/', meaning: '姐妹', example: 'She is my older sister.', category: 'english' },
  { id: 'e39', term: 'Baby', pronunciation: '/ˈbeɪ.bi/', meaning: '婴儿', example: 'The baby is crying loudly.', category: 'english' },
  { id: 'e40', term: 'Teacher', pronunciation: '/ˈtiː.tʃər/', meaning: '老师', example: 'My teacher is very kind and helpful.', category: 'english' },
  { id: 'e41', term: 'Doctor', pronunciation: '/ˈdɒk.tər/', meaning: '医生', example: 'The doctor helps sick people get better.', category: 'english' },
  { id: 'e42', term: 'Nurse', pronunciation: '/nɜːs/', meaning: '护士', example: 'Nurses take care of patients in hospitals.', category: 'english' },
  { id: 'e43', term: 'Student', pronunciation: '/ˈstjuː.dənt/', meaning: '学生', example: 'I am a good student at school.', category: 'english' },
  { id: 'e44', term: 'Friend', pronunciation: '/frend/', meaning: '朋友', example: 'I have many good friends at school.', category: 'english' },
  { id: 'e45', term: 'Classmate', pronunciation: '/ˈklɑːs.meɪt/', meaning: '同学', example: 'My classmate helps me with math.', category: 'english' },
  { id: 'e46', term: 'Grandfather', pronunciation: '/ˈɡrænd.fɑː.ðər/', meaning: '爷爷', example: 'My grandfather tells me interesting stories.', category: 'english' },
  { id: 'e47', term: 'Grandmother', pronunciation: '/ˈɡrænd.mʌð.ər/', meaning: '奶奶', example: 'My grandmother makes delicious cookies.', category: 'english' },
  { id: 'e48', term: 'Cousin', pronunciation: '/ˈkʌz.ən/', meaning: '表兄弟姐妹', example: 'My cousin lives in Beijing.', category: 'english' },

  // School & Common Objects
  { id: 'e49', term: 'School', pronunciation: '/skuːl/', meaning: '学校', example: 'I go to school by bus every day.', category: 'english' },
  { id: 'e50', term: 'Book', pronunciation: '/bʊk/', meaning: '书', example: 'Open your book to page 10.', category: 'english' },
  { id: 'e51', term: 'Pen', pronunciation: '/pen/', meaning: '钢笔', example: 'I write with a blue pen.', category: 'english' },
  { id: 'e52', term: 'Pencil', pronunciation: '/ˈpen.səl/', meaning: '铅笔', example: 'Sharpen your pencil before writing.', category: 'english' },
  { id: 'e53', term: 'Bag', pronunciation: '/bæɡ/', meaning: '书包', example: 'My school bag is heavy today.', category: 'english' },
  { id: 'e54', term: 'Desk', pronunciation: '/desk/', meaning: '课桌', example: 'Sit quietly at your desk.', category: 'english' },
  { id: 'e55', term: 'Chair', pronunciation: '/tʃeər/', meaning: '椅子', example: 'The chair is comfortable to sit on.', category: 'english' },
  { id: 'e56', term: 'Computer', pronunciation: '/kəmˈpjuː.tər/', meaning: '电脑', example: 'I use the computer for learning.', category: 'english' },
  { id: 'e57', term: 'Notebook', pronunciation: '/ˈnəʊt.bʊk/', meaning: '笔记本', example: 'Write down your homework in your notebook.', category: 'english' },
  { id: 'e58', term: 'Eraser', pronunciation: '/ɪˈreɪ.zər/', meaning: '橡皮擦', example: 'Use the eraser to correct mistakes.', category: 'english' },
  { id: 'e59', term: 'Ruler', pronunciation: '/ˈruː.lər/', meaning: '尺子', example: 'Use the ruler to draw a straight line.', category: 'english' },
  { id: 'e60', term: 'Pencil Case', pronunciation: '/ˈpen.səl keɪs/', meaning: '铅笔盒', example: 'Put your pencils in the pencil case.', category: 'english' },
  { id: 'e61', term: 'Blackboard', pronunciation: '/ˈblæk.bɔːd/', meaning: '黑板', example: 'The teacher writes on the blackboard.', category: 'english' },
  { id: 'e62', term: 'Whiteboard', pronunciation: '/ˈwaɪt.bɔːd/', meaning: '白板', example: 'We use markers on the whiteboard.', category: 'english' },
  { id: 'e63', term: 'Clock', pronunciation: '/klɒk/', meaning: '钟', example: 'The clock shows the time for class.', category: 'english' },

  // Body Parts
  { id: 'e64', term: 'Head', pronunciation: '/hed/', meaning: '头', example: 'Nod your head if you understand.', category: 'english' },
  { id: 'e65', term: 'Eye', pronunciation: '/aɪ/', meaning: '眼睛', example: 'Close your eyes and sleep.', category: 'english' },
  { id: 'e66', term: 'Nose', pronunciation: '/nəʊz/', meaning: '鼻子', example: 'You can smell with your nose.', category: 'english' },
  { id: 'e67', term: 'Mouth', pronunciation: '/maʊθ/', meaning: '嘴', example: 'Open your mouth and say "Ah".', category: 'english' },
  { id: 'e68', term: 'Ear', pronunciation: '/ɪər/', meaning: '耳朵', example: 'Listen carefully with your ears.', category: 'english' },
  { id: 'e69', term: 'Hand', pronunciation: '/hænd/', meaning: '手', example: 'Wash your hands before eating.', category: 'english' },
  { id: 'e70', term: 'Foot', pronunciation: '/fʊt/', meaning: '脚', example: 'Stomp your feet to the music.', category: 'english' },
  { id: 'e71', term: 'Arm', pronunciation: '/ɑːm/', meaning: '手臂', example: 'Raise your arm to answer the question.', category: 'english' },
  { id: 'e72', term: 'Leg', pronunciation: '/leɡ/', meaning: '腿', example: 'You can walk with your legs.', category: 'english' },
  { id: 'e73', term: 'Hair', pronunciation: '/heər/', meaning: '头发', example: 'My hair is black and long.', category: 'english' },
  { id: 'e74', term: 'Face', pronunciation: '/feɪs/', meaning: '脸', example: 'Wash your face in the morning.', category: 'english' },
  { id: 'e75', term: 'Tooth', pronunciation: '/tuːθ/', meaning: '牙齿', example: 'Brush your teeth twice a day.', category: 'english' },
  { id: 'e76', term: 'Tongue', pronunciation: '/tʌŋ/', meaning: '舌头', example: 'You can taste with your tongue.', category: 'english' },

  // Common Verbs
  { id: 'e77', term: 'Run', pronunciation: '/rʌn/', meaning: '跑', example: 'Run fast to catch the bus.', category: 'english' },
  { id: 'e78', term: 'Jump', pronunciation: '/dʒʌmp/', meaning: '跳', example: 'Jump over the small fence.', category: 'english' },
  { id: 'e79', term: 'Sleep', pronunciation: '/sliːp/', meaning: '睡觉', example: 'Children need to sleep for 8-10 hours.', category: 'english' },
  { id: 'e80', term: 'Eat', pronunciation: '/iːt/', meaning: '吃', example: 'Eat healthy food every day.', category: 'english' },
  { id: 'e81', term: 'Drink', pronunciation: '/drɪŋk/', meaning: '喝', example: 'Drink plenty of water daily.', category: 'english' },
  { id: 'e82', term: 'Play', pronunciation: '/pleɪ/', meaning: '玩', example: 'Let\'s play football after school.', category: 'english' },
  { id: 'e83', term: 'Sing', pronunciation: '/sɪŋ/', meaning: '唱', example: 'Sing a song for your friends.', category: 'english' },
  { id: 'e84', term: 'Dance', pronunciation: '/dɑːns/', meaning: '跳舞', example: 'Do you like to dance at parties?', category: 'english' },
  { id: 'e85', term: 'Swim', pronunciation: '/swɪm/', meaning: '游泳', example: 'I can swim in the swimming pool.', category: 'english' },
  { id: 'e86', term: 'Read', pronunciation: '/riːd/', meaning: '读', example: 'Read books to learn new things.', category: 'english' },
  { id: 'e87', term: 'Write', pronunciation: '/raɪt/', meaning: '写', example: 'Write a letter to your pen pal.', category: 'english' },
  { id: 'e88', term: 'Listen', pronunciation: '/ˈlɪs.ən/', meaning: '听', example: 'Listen to the teacher carefully.', category: 'english' },
  { id: 'e89', term: 'Speak', pronunciation: '/spiːk/', meaning: '说', example: 'Speak English loudly and clearly.', category: 'english' },
  { id: 'e90', term: 'Walk', pronunciation: '/wɔːk/', meaning: '走', example: 'Let\'s walk to the park together.', category: 'english' },
  { id: 'e91', term: 'Draw', pronunciation: '/drɔː/', meaning: '画', example: 'Draw a picture of your family.', category: 'english' },
  { id: 'e92', term: 'Paint', pronunciation: '/peɪnt/', meaning: '画', example: 'Paint a colorful picture with watercolors.', category: 'english' },
  { id: 'e93', term: 'Study', pronunciation: '/ˈstʌd.i/', meaning: '学习', example: 'Study hard for your exams.', category: 'english' },
  { id: 'e94', term: 'Work', pronunciation: '/wɜːk/', meaning: '工作', example: 'My parents work in offices.', category: 'english' },
  { id: 'e95', term: 'Help', pronunciation: '/help/', meaning: '帮助', example: 'Help your friends when they need it.', category: 'english' },
  { id: 'e96', term: 'Clean', pronunciation: '/kliːn/', meaning: '打扫', example: 'Clean your room every weekend.', category: 'english' },
  
  // Food & Drink
  { id: 'e97', term: 'Banana', pronunciation: '/bəˈnɑː.nə/', meaning: '香蕉', example: 'Monkeys and children love bananas.', category: 'english' },
  { id: 'e98', term: 'Bread', pronunciation: '/bred/', meaning: '面包', example: 'I eat bread with butter for breakfast.', category: 'english' },
  { id: 'e99', term: 'Milk', pronunciation: '/mɪlk/', meaning: '牛奶', example: 'Milk helps build strong bones and teeth.', category: 'english' },
  { id: 'e100', term: 'Water', pronunciation: '/ˈwɔː.tər/', meaning: '水', example: 'Drink clean water every day.', category: 'english' },
  { id: 'e101', term: 'Egg', pronunciation: '/eɡ/', meaning: '鸡蛋', example: 'I want a fried egg for breakfast.', category: 'english' },
  { id: 'e102', term: 'Ice Cream', pronunciation: '/ˈaɪs ˌkriːm/', meaning: '冰淇淋', example: 'Chocolate ice cream is my favorite.', category: 'english' },
  { id: 'e103', term: 'Rice', pronunciation: '/raɪs/', meaning: '米饭', example: 'Chinese people often eat rice for dinner.', category: 'english' },
  { id: 'e104', term: 'Noodles', pronunciation: '/ˈnuː.dəlz/', meaning: '面条', example: 'I like eating noodles with vegetables.', category: 'english' },
  { id: 'e105', term: 'Chocolate', pronunciation: '/ˈtʃɒk.əl.ɪt/', meaning: '巧克力', example: 'Chocolate is sweet and delicious.', category: 'english' },
  { id: 'e106', term: 'Cake', pronunciation: '/keɪk/', meaning: '蛋糕', example: 'We eat cake on birthdays.', category: 'english' },
  { id: 'e107', term: 'Cookie', pronunciation: '/ˈkʊk.i/', meaning: '饼干', example: 'Grandma makes the best cookies.', category: 'english' },
  { id: 'e108', term: 'Fruit', pronunciation: '/fruːt/', meaning: '水果', example: 'Eat fresh fruit every day for vitamins.', category: 'english' },
  { id: 'e109', term: 'Vegetable', pronunciation: '/ˈvedʒ.tə.bəl/', meaning: '蔬菜', example: 'Eat more vegetables to stay healthy.', category: 'english' },
  { id: 'e110', term: 'Meat', pronunciation: '/miːt/', meaning: '肉', example: 'Chicken meat is healthy for you.', category: 'english' },
  { id: 'e111', term: 'Fish', pronunciation: '/fɪʃ/', meaning: '鱼', example: 'Fish is good for your brain.', category: 'english' },
  { id: 'e112', term: 'Soup', pronunciation: '/suːp/', meaning: '汤', example: 'Drink warm soup when you are sick.', category: 'english' },
  { id: 'e113', term: 'Tea', pronunciation: '/tiː/', meaning: '茶', example: 'My parents drink tea in the afternoon.', category: 'english' },
  { id: 'e114', term: 'Coffee', pronunciation: '/ˈkɒf.i/', meaning: '咖啡', example: 'Some adults drink coffee in the morning.', category: 'english' },
  { id: 'e115', term: 'Juice', pronunciation: '/dʒuːs/', meaning: '果汁', example: 'Orange juice is rich in vitamin C.', category: 'english' },

  // Daily Life & Weather
  { id: 'e116', term: 'House', pronunciation: '/haʊs/', meaning: '房子', example: 'I live in a big house with my family.', category: 'english' },
  { id: 'e117', term: 'Home', pronunciation: '/həʊm/', meaning: '家', example: 'Home is where the heart is.', category: 'english' },
  { id: 'e118', term: 'Room', pronunciation: '/ruːm/', meaning: '房间', example: 'My bedroom is my favorite room.', category: 'english' },
  { id: 'e119', term: 'Bed', pronunciation: '/bed/', meaning: '床', example: 'I sleep in a comfortable bed.', category: 'english' },
  { id: 'e120', term: 'Window', pronunciation: '/ˈwɪn.dəʊ/', meaning: '窗户', example: 'Open the window for fresh air.', category: 'english' },
  { id: 'e121', term: 'Door', pronunciation: '/dɔː(r)/', meaning: '门', example: 'Close the door when you leave.', category: 'english' },
  { id: 'e122', term: 'Sky', pronunciation: '/skaɪ/', meaning: '天空', example: 'The sky is blue on sunny days.', category: 'english' },
  { id: 'e123', term: 'Sun', pronunciation: '/sʌn/', meaning: '太阳', example: 'The sun gives us light and heat.', category: 'english' },
  { id: 'e124', term: 'Moon', pronunciation: '/muːn/', meaning: '月亮', example: 'The moon shines at night.', category: 'english' },
  { id: 'e125', term: 'Star', pronunciation: '/stɑː(r)/', meaning: '星星', example: 'There are many stars in the sky at night.', category: 'english' },
  { id: 'e126', term: 'Cloud', pronunciation: '/klaʊd/', meaning: '云', example: 'White clouds float in the sky.', category: 'english' },
  { id: 'e127', term: 'Rain', pronunciation: '/reɪn/', meaning: '雨', example: 'We need rain for plants to grow.', category: 'english' },
  { id: 'e128', term: 'Snow', pronunciation: '/snəʊ/', meaning: '雪', example: 'We can make snowmen in winter.', category: 'english' },
  { id: 'e129', term: 'Wind', pronunciation: '/wɪnd/', meaning: '风', example: 'The wind blows the leaves.', category: 'english' },
  { id: 'e130', term: 'Weather', pronunciation: '/ˈweð.ər/', meaning: '天气', example: 'What is the weather like today?', category: 'english' },
  { id: 'e131', term: 'Temperature', pronunciation: '/ˈtem.prə.tʃər/', meaning: '温度', example: 'The temperature is 25 degrees today.', category: 'english' },
  { id: 'e132', term: 'Season', pronunciation: '/ˈsiː.zən/', meaning: '季节', example: 'There are four seasons in a year.', category: 'english' },
  { id: 'e133', term: 'Spring', pronunciation: '/sprɪŋ/', meaning: '春天', example: 'Flowers bloom in spring.', category: 'english' },
  { id: 'e134', term: 'Summer', pronunciation: '/ˈsʌm.ə/', meaning: '夏天', example: 'It is hot in summer.', category: 'english' },
  { id: 'e135', term: 'Autumn', pronunciation: '/ˈɔː.təm/', meaning: '秋天', example: 'Leaves fall in autumn.', category: 'english' },
  { id: 'e136', term: 'Winter', pronunciation: '/ˈwɪn.tə/', meaning: '冬天', example: 'It is cold in winter.', category: 'english' },

  // Transportation
  { id: 'e137', term: 'Car', pronunciation: '/kɑː(r)/', meaning: '汽车', example: 'My father drives a red car.', category: 'english' },
  { id: 'e138', term: 'Bus', pronunciation: '/bʌs/', meaning: '公交车', example: 'I take the bus to school every day.', category: 'english' },
  { id: 'e139', term: 'Train', pronunciation: '/treɪn/', meaning: '火车', example: 'Trains are good for long journeys.', category: 'english' },
  { id: 'e140', term: 'Airplane', pronunciation: '/ˈeə.pleɪn/', meaning: '飞机', example: 'Airplanes fly high in the sky.', category: 'english' },
  { id: 'e141', term: 'Ship', pronunciation: '/ʃɪp/', meaning: '船', example: 'Ships sail on the ocean.', category: 'english' },
  { id: 'e142', term: 'Boat', pronunciation: '/bəʊt/', meaning: '小船', example: 'We rowed a boat on the lake.', category: 'english' },
  { id: 'e143', term: 'Bicycle', pronunciation: '/ˈbaɪ.sɪ.kəl/', meaning: '自行车', example: 'I ride my bicycle to the park.', category: 'english' },
  { id: 'e144', term: 'Motorcycle', pronunciation: '/ˈməʊ.tə.saɪ.kəl/', meaning: '摩托车', example: 'Motorcycles are faster than bicycles.', category: 'english' },
  { id: 'e145', term: 'Taxi', pronunciation: '/ˈtæk.si/', meaning: '出租车', example: 'We took a taxi to the airport.', category: 'english' },
  { id: 'e146', term: 'Subway', pronunciation: '/ˈsʌb.weɪ/', meaning: '地铁', example: 'The subway is fast and convenient.', category: 'english' },

  // Numbers & Math
  { id: 'e147', term: 'One', pronunciation: '/wʌn/', meaning: '一', example: 'I have one pencil.', category: 'english' },
  { id: 'e148', term: 'Two', pronunciation: '/tuː/', meaning: '二', example: 'There are two apples on the table.', category: 'english' },
  { id: 'e149', term: 'Three', pronunciation: '/θriː/', meaning: '三', example: 'Three plus three equals six.', category: 'english' },
  { id: 'e150', term: 'Four', pronunciation: '/fɔː(r)/', meaning: '四', example: 'Four seasons make a year.', category: 'english' },
  { id: 'e151', term: 'Five', pronunciation: '/faɪv/', meaning: '五', example: 'Five fingers on each hand.', category: 'english' },
  { id: 'e152', term: 'Six', pronunciation: '/sɪks/', meaning: '六', example: 'Six days a week I go to school.', category: 'english' },
  { id: 'e153', term: 'Seven', pronunciation: '/ˈsev.ən/', meaning: '七', example: 'Seven colors in the rainbow.', category: 'english' },
  { id: 'e154', term: 'Eight', pronunciation: '/eɪt/', meaning: '八', example: 'Eight o\'clock is bedtime.', category: 'english' },
  { id: 'e155', term: 'Nine', pronunciation: '/naɪn/', meaning: '九', example: 'Nine students are in the classroom.', category: 'english' },
  { id: 'e156', term: 'Ten', pronunciation: '/ten/', meaning: '十', example: 'Ten is my favorite number.', category: 'english' },
  { id: 'e157', term: 'Eleven', pronunciation: '/ɪˈlev.ən/', meaning: '十一', example: 'I am eleven years old.', category: 'english' },
  { id: 'e158', term: 'Twelve', pronunciation: '/twelv/', meaning: '十二', example: 'There are twelve months in a year.', category: 'english' },
  { id: 'e159', term: 'Twenty', pronunciation: '/ˈtwen.ti/', meaning: '二十', example: 'Twenty children are in our class.', category: 'english' },
  { id: 'e160', term: 'Thirty', pronunciation: '/ˈθɜː.ti/', meaning: '三十', example: 'Thirty days has September.', category: 'english' },
  { id: 'e161', term: 'One Hundred', pronunciation: '/wʌn ˈhʌn.drəd/', meaning: '一百', example: 'One hundred is a big number.', category: 'english' },
  { id: 'e162', term: 'Number', pronunciation: '/ˈnʌm.bər/', meaning: '数字', example: 'Count the numbers from one to ten.', category: 'english' },
  { id: 'e163', term: 'Plus', pronunciation: '/plʌs/', meaning: '加', example: 'Two plus three equals five.', category: 'english' },
  { id: 'e164', term: 'Minus', pronunciation: '/ˈmaɪ.nəs/', meaning: '减', example: 'Five minus two equals three.', category: 'english' },
  { id: 'e165', term: 'Equal', pronunciation: '/ˈiː.kwəl/', meaning: '等于', example: 'Two plus two equals four.', category: 'english' },
  { id: 'e166', term: 'Add', pronunciation: '/æd/', meaning: '加', example: 'Add these numbers together.', category: 'english' },
  { id: 'e167', term: 'Subtract', pronunciation: '/səbˈtrækt/', meaning: '减', example: 'Subtract the smaller number from the larger one.', category: 'english' },
  { id: 'e168', term: 'Multiply', pronunciation: '/ˈmʌl.tɪ.plaɪ/', meaning: '乘', example: 'Three multiply by four is twelve.', category: 'english' },
  { id: 'e169', term: 'Divide', pronunciation: '/dɪˈvaɪd/', meaning: '除', example: 'Twelve divide by three is four.', category: 'english' },
  { id: 'e170', term: 'Sum', pronunciation: '/sʌm/', meaning: '和', example: 'The sum of two and three is five.', category: 'english' }
];