import { LearningItem } from './types';
export const ENGLISH_GRADE_3B: LearningItem[] = [
  // 三年级下册 - 第一单元：科学与探索 (Science & Exploration)
  { id: "3B-1-1", term: "science", pronunciation: "/ˈsaɪəns/", meaning: "科学", example: "I love studying science. 我喜欢学习科学。", category: "english", grade: "三年级下", unit: "第一单元", subcategory: "science", isWritable: true },
  { id: "3B-1-2", term: "experiment", pronunciation: "/ɪkˈsperɪmənt/", meaning: "实验", example: "We did an experiment in class. 我们在课堂上做了一个实验。", category: "english", grade: "三年级下", unit: "第一单元", subcategory: "science", isWritable: true },
  { id: "3B-1-3", term: "discover", pronunciation: "/dɪˈskʌvər/", meaning: "发现", example: "Scientists discover new things every day. 科学家每天都有新发现。", category: "english", grade: "三年级下", unit: "第一单元", subcategory: "science", isWritable: true },
  { id: "3B-1-4", term: "planet", pronunciation: "/ˈplænɪt/", meaning: "行星", example: "Earth is our planet. 地球是我们的行星。", category: "english", grade: "三年级下", unit: "第一单元", subcategory: "science", isWritable: true },
  { id: "3B-1-5", term: "star", pronunciation: "/stɑːr/", meaning: "星星", example: "The sky is full of stars at night. 夜晚的天空布满星星。", category: "english", grade: "三年级下", unit: "第一单元", subcategory: "science", isWritable: true },
  { id: "3B-1-6", term: "moon", pronunciation: "/muːn/", meaning: "月亮", example: "The moon is bright tonight. 今晚月亮很亮。", category: "english", grade: "三年级下", unit: "第一单元", subcategory: "science", isWritable: true },
  { id: "3B-1-7", term: "sun", pronunciation: "/sʌn/", meaning: "太阳", example: "The sun gives us light and heat. 太阳给我们光和热。", category: "english", grade: "三年级下", unit: "第一单元", subcategory: "science", isWritable: true },
  { id: "3B-1-8", term: "earth", pronunciation: "/ɜːrθ/", meaning: "地球", example: "We should protect the earth. 我们应该保护地球。", category: "english", grade: "三年级下", unit: "第一单元", subcategory: "science", isWritable: true },
  { id: "3B-1-9", term: "flower", pronunciation: "/ˈflaʊər/", meaning: "花", example: "The flower is beautiful. 这朵花很漂亮。", category: "english", grade: "三年级下", unit: "第一单元", subcategory: "science", isWritable: true },
  { id: "3B-1-10", term: "leaf", pronunciation: "/liːf/", meaning: "叶子", example: "The leaf turns yellow in autumn. 叶子在秋天变黄。", category: "english", grade: "三年级下", unit: "第一单元", subcategory: "science", isWritable: true },
  { id: "3B-1-11", term: "root", pronunciation: "/ruːt/", meaning: "根", example: "Plants have roots in the soil. 植物在土壤里有根。", category: "english", grade: "三年级下", unit: "第一单元", subcategory: "science", isWritable: true },
  { id: "3B-1-12", term: "stem", pronunciation: "/stem/", meaning: "茎", example: "The stem holds the flower up. 茎支撑着花。", category: "english", grade: "三年级下", unit: "第一单元", subcategory: "science", isWritable: true },
  { id: "3B-1-13", term: "seed", pronunciation: "/siːd/", meaning: "种子", example: "A seed grows into a plant. 种子长成植物。", category: "english", grade: "三年级下", unit: "第一单元", subcategory: "science", isWritable: true },
  { id: "3B-1-14", term: "water", pronunciation: "/ˈwɔːtər/", meaning: "水", example: "Plants need water to grow. 植物需要水来生长。", category: "english", grade: "三年级下", unit: "第一单元", subcategory: "science", isWritable: true },
  { id: "3B-1-15", term: "soil", pronunciation: "/sɔɪl/", meaning: "土壤", example: "Seeds grow in the soil. 种子在土壤里生长。", category: "english", grade: "三年级下", unit: "第一单元", subcategory: "science", isWritable: true },
  { id: "3B-1-16", term: "light", pronunciation: "/laɪt/", meaning: "光", example: "Plants need light from the sun. 植物需要来自太阳的光。", category: "english", grade: "三年级下", unit: "第一单元", subcategory: "science", isWritable: true },
  { id: "3B-1-17", term: "shadow", pronunciation: "/ˈʃædoʊ/", meaning: "影子", example: "The tree has a long shadow. 树有长长的影子。", category: "english", grade: "三年级下", unit: "第一单元", subcategory: "science", isWritable: true },
  { id: "3B-1-18", term: "magnet", pronunciation: "/ˈmæɡnət/", meaning: "磁铁", example: "A magnet attracts metal. 磁铁吸引金属。", category: "english", grade: "三年级下", unit: "第一单元", subcategory: "science", isWritable: true },

  // 三年级下册 - 第二单元：健康与生活 (Health & Lifestyle)
  { id: "3B-2-1", term: "healthy", pronunciation: "/ˈhelθi/", meaning: "健康的", example: "Eating fruits makes us healthy. 吃水果使我们健康。", category: "english", grade: "三年级下", unit: "第二单元", subcategory: "health", isWritable: true },
  { id: "3B-2-2", term: "exercise", pronunciation: "/ˈeksərsaɪz/", meaning: "锻炼", example: "I do exercise every day. 我每天都锻炼。", category: "english", grade: "三年级下", unit: "第二单元", subcategory: "health", isWritable: true },
  { id: "3B-2-3", term: "diet", pronunciation: "/ˈdaɪət/", meaning: "饮食", example: "We need a balanced diet. 我们需要均衡的饮食。", category: "english", grade: "三年级下", unit: "第二单元", subcategory: "health", isWritable: true },
  { id: "3B-2-4", term: "sleep", pronunciation: "/sliːp/", meaning: "睡觉", example: "Children need 10 hours of sleep. 儿童需要10小时的睡眠。", category: "english", grade: "三年级下", unit: "第二单元", subcategory: "health", isWritable: true },
  { id: "3B-2-5", term: "hygiene", pronunciation: "/ˈhaɪdʒiːn/", meaning: "卫生", example: "Good hygiene keeps us clean. 良好的卫生使我们保持清洁。", category: "english", grade: "三年级下", unit: "第二单元", subcategory: "health", isWritable: true },
  { id: "3B-2-6", term: "brush", pronunciation: "/brʌʃ/", meaning: "刷", example: "Brush your teeth twice a day. 每天刷两次牙。", category: "english", grade: "三年级下", unit: "第二单元", subcategory: "health", isWritable: true },
  { id: "3B-2-7", term: "wash", pronunciation: "/wɑːʃ/", meaning: "洗", example: "Wash your hands before eating. 吃饭前洗手。", category: "english", grade: "三年级下", unit: "第二单元", subcategory: "health", isWritable: true },
  { id: "3B-2-8", term: "eat", pronunciation: "/iːt/", meaning: "吃", example: "Eat your vegetables. 吃你的蔬菜。", category: "english", grade: "三年级下", unit: "第二单元", subcategory: "health", isWritable: true },
  { id: "3B-2-9", term: "drink", pronunciation: "/drɪŋk/", meaning: "喝", example: "Drink more water. 多喝水。", category: "english", grade: "三年级下", unit: "第二单元", subcategory: "health", isWritable: true },
  { id: "3B-2-10", term: "fruit", pronunciation: "/fruːt/", meaning: "水果", example: "I like to eat fruit. 我喜欢吃水果。", category: "english", grade: "三年级下", unit: "第二单元", subcategory: "health", isWritable: true },
  { id: "3B-2-11", term: "vegetable", pronunciation: "/ˈvedʒtəbl/", meaning: "蔬菜", example: "Vegetables are good for us. 蔬菜对我们有好处。", category: "english", grade: "三年级下", unit: "第二单元", subcategory: "health", isWritable: true },
  { id: "3B-2-12", term: "meat", pronunciation: "/miːt/", meaning: "肉", example: "Chicken is a kind of meat. 鸡肉是一种肉。", category: "english", grade: "三年级下", unit: "第二单元", subcategory: "health", isWritable: true },
  { id: "3B-2-13", term: "fish", pronunciation: "/fɪʃ/", meaning: "鱼", example: "Fish is good for the brain. 鱼对大脑有好处。", category: "english", grade: "三年级下", unit: "第二单元", subcategory: "health", isWritable: true },
  { id: "3B-2-14", term: "milk", pronunciation: "/mɪlk/", meaning: "牛奶", example: "I drink milk every morning. 我每天早上喝牛奶。", category: "english", grade: "三年级下", unit: "第二单元", subcategory: "health", isWritable: true },
  { id: "3B-2-15", term: "bread", pronunciation: "/bred/", meaning: "面包", example: "I eat bread for breakfast. 我早餐吃面包。", category: "english", grade: "三年级下", unit: "第二单元", subcategory: "health", isWritable: true },
  { id: "3B-2-16", term: "egg", pronunciation: "/eɡ/", meaning: "鸡蛋", example: "An egg has protein. 鸡蛋含有蛋白质。", category: "english", grade: "三年级下", unit: "第二单元", subcategory: "health", isWritable: true },
  { id: "3B-2-17", term: "rice", pronunciation: "/raɪs/", meaning: "米饭", example: "Chinese people eat rice every day. 中国人每天吃米饭。", category: "english", grade: "三年级下", unit: "第二单元", subcategory: "health", isWritable: true },
  { id: "3B-2-18", term: "noodle", pronunciation: "/ˈnuːdl/", meaning: "面条", example: "I like to eat noodles. 我喜欢吃面条。", category: "english", grade: "三年级下", unit: "第二单元", subcategory: "health", isWritable: true },

  // 三年级下册 - 第三单元：旅行与交通 (Travel & Transportation)
  { id: "3B-3-1", term: "travel", pronunciation: "/ˈtrævl/", meaning: "旅行", example: "I love to travel with my family. 我喜欢和家人一起旅行。", category: "english", grade: "三年级下", unit: "第三单元", subcategory: "travel", isWritable: true },
  { id: "3B-3-2", term: "trip", pronunciation: "/trɪp/", meaning: "旅行", example: "We had a nice trip to the park. 我们去公园玩得很开心。", category: "english", grade: "三年级下", unit: "第三单元", subcategory: "travel", isWritable: true },
  { id: "3B-3-3", term: "airport", pronunciation: "/ˈerpɔːrt/", meaning: "机场", example: "We went to the airport to catch a plane. 我们去机场赶飞机。", category: "english", grade: "三年级下", unit: "第三单元", subcategory: "travel", isWritable: true },
  { id: "3B-3-4", term: "train", pronunciation: "/treɪn/", meaning: "火车", example: "I took a train to Beijing. 我坐火车去北京。", category: "english", grade: "三年级下", unit: "第三单元", subcategory: "travel", isWritable: true },
  { id: "3B-3-5", term: "bus", pronunciation: "/bʌs/", meaning: "公共汽车", example: "I take the bus to school. 我坐公共汽车去上学。", category: "english", grade: "三年级下", unit: "第三单元", subcategory: "travel", isWritable: true },
  { id: "3B-3-6", term: "car", pronunciation: "/kɑːr/", meaning: "汽车", example: "My dad drives a car to work. 我爸爸开车去上班。", category: "english", grade: "三年级下", unit: "第三单元", subcategory: "travel", isWritable: true },
  { id: "3B-3-7", term: "bike", pronunciation: "/baɪk/", meaning: "自行车", example: "I ride a bike to school. 我骑自行车去上学。", category: "english", grade: "三年级下", unit: "第三单元", subcategory: "travel", isWritable: true },
  { id: "3B-3-8", term: "plane", pronunciation: "/pleɪn/", meaning: "飞机", example: "The plane is flying in the sky. 飞机在天空中飞行。", category: "english", grade: "三年级下", unit: "第三单元", subcategory: "travel", isWritable: true },
  { id: "3B-3-9", term: "ship", pronunciation: "/ʃɪp/", meaning: "船", example: "The ship is sailing on the sea. 船在海上航行。", category: "english", grade: "三年级下", unit: "第三单元", subcategory: "travel", isWritable: true },
  { id: "3B-3-10", term: "boat", pronunciation: "/boʊt/", meaning: "小船", example: "We rowed a boat on the lake. 我们在湖上划船。", category: "english", grade: "三年级下", unit: "第三单元", subcategory: "travel", isWritable: true },
  { id: "3B-3-11", term: "map", pronunciation: "/mæp/", meaning: "地图", example: "We used a map to find our way. 我们用地图找路。", category: "english", grade: "三年级下", unit: "第三单元", subcategory: "travel", isWritable: true },
  { id: "3B-3-12", term: "ticket", pronunciation: "/ˈtɪkɪt/", meaning: "票", example: "I bought a ticket for the movie. 我买了一张电影票。", category: "english", grade: "三年级下", unit: "第三单元", subcategory: "travel", isWritable: true },
  { id: "3B-3-13", term: "hotel", pronunciation: "/hoʊˈtel/", meaning: "酒店", example: "We stayed in a nice hotel. 我们住在一家不错的酒店里。", category: "english", grade: "三年级下", unit: "第三单元", subcategory: "travel", isWritable: true },
  { id: "3B-3-14", term: "restaurant", pronunciation: "/ˈrestərɑːnt/", meaning: "餐厅", example: "We ate dinner at a restaurant. 我们在餐厅吃晚餐。", category: "english", grade: "三年级下", unit: "第三单元", subcategory: "travel", isWritable: true },
  { id: "3B-3-15", term: "sightseeing", pronunciation: "/ˈsaɪtsiːɪŋ/", meaning: "观光", example: "We went sightseeing in the city. 我们在城里观光。", category: "english", grade: "三年级下", unit: "第三单元", subcategory: "travel", isWritable: true },
  { id: "3B-3-16", term: "beach", pronunciation: "/biːtʃ/", meaning: "海滩", example: "We played on the beach. 我们在海滩上玩。", category: "english", grade: "三年级下", unit: "第三单元", subcategory: "travel", isWritable: true },
  { id: "3B-3-17", term: "mountain", pronunciation: "/ˈmaʊntn/", meaning: "山", example: "We climbed the mountain. 我们爬了那座山。", category: "english", grade: "三年级下", unit: "第三单元", subcategory: "travel", isWritable: true },

  // 三年级下册 - 第四单元：文化与传统 (Culture & Traditions)
  { id: "3B-4-1", term: "culture", pronunciation: "/ˈkʌltʃər/", meaning: "文化", example: "Chinese culture is very rich. 中国文化非常丰富。", category: "english", grade: "三年级下", unit: "第四单元", subcategory: "culture", isWritable: true },
  { id: "3B-4-2", term: "tradition", pronunciation: "/trəˈdɪʃn/", meaning: "传统", example: "We have many traditions. 我们有很多传统。", category: "english", grade: "三年级下", unit: "第四单元", subcategory: "culture", isWritable: true },
  { id: "3B-4-3", term: "festival", pronunciation: "/ˈfestɪvl/", meaning: "节日", example: "Spring Festival is the most important festival in China. 春节是中国最重要的节日。", category: "english", grade: "三年级下", unit: "第四单元", subcategory: "culture", isWritable: true },
  { id: "3B-4-4", term: "holiday", pronunciation: "/ˈhɑːlədeɪ/", meaning: "假期", example: "We have a holiday on National Day. 国庆节我们有假期。", category: "english", grade: "三年级下", unit: "第四单元", subcategory: "culture", isWritable: true },
  { id: "3B-4-5", term: "custom", pronunciation: "/ˈkʌstəm/", meaning: "习俗", example: "It's a custom to eat dumplings on Spring Festival. 春节吃饺子是一种习俗。", category: "english", grade: "三年级下", unit: "第四单元", subcategory: "culture", isWritable: true },
  { id: "3B-4-6", term: "food", pronunciation: "/fuːd/", meaning: "食物", example: "Chinese food is delicious. 中国食物很美味。", category: "english", grade: "三年级下", unit: "第四单元", subcategory: "culture", isWritable: true },
  { id: "3B-4-7", term: "dumpling", pronunciation: "/ˈdʌmplɪŋ/", meaning: "饺子", example: "I like to eat dumplings. 我喜欢吃饺子。", category: "english", grade: "三年级下", unit: "第四单元", subcategory: "culture", isWritable: true },
  { id: "3B-4-8", term: "rice", pronunciation: "/raɪs/", meaning: "米饭", example: "We eat rice every day. 我们每天吃米饭。", category: "english", grade: "三年级下", unit: "第四单元", subcategory: "culture", isWritable: true },
  { id: "3B-4-9", term: "noodle", pronunciation: "/ˈnuːdl/", meaning: "面条", example: "Long noodles mean long life. 长面条意味着长寿。", category: "english", grade: "三年级下", unit: "第四单元", subcategory: "culture", isWritable: true },
  { id: "3B-4-10", term: "cake", pronunciation: "/keɪk/", meaning: "蛋糕", example: "We eat cake on birthdays. 我们在生日时吃蛋糕。", category: "english", grade: "三年级下", unit: "第四单元", subcategory: "culture", isWritable: true },
  { id: "3B-4-11", term: "song", pronunciation: "/sɔːŋ/", meaning: "歌曲", example: "We sing songs at festivals. 我们在节日里唱歌。", category: "english", grade: "三年级下", unit: "第四单元", subcategory: "culture", isWritable: true },
  { id: "3B-4-12", term: "dance", pronunciation: "/dæns/", meaning: "舞蹈", example: "We dance at parties. 我们在派对上跳舞。", category: "english", grade: "三年级下", unit: "第四单元", subcategory: "culture", isWritable: true },
  { id: "3B-4-13", term: "story", pronunciation: "/ˈstɔːri/", meaning: "故事", example: "Grandma tells me stories. 奶奶给我讲故事。", category: "english", grade: "三年级下", unit: "第四单元", subcategory: "culture", isWritable: true },
  { id: "3B-4-14", term: "book", pronunciation: "/bʊk/", meaning: "书", example: "I like to read books. 我喜欢读书。", category: "english", grade: "三年级下", unit: "第四单元", subcategory: "culture", isWritable: true },
  { id: "3B-4-15", term: "art", pronunciation: "/ɑːrt/", meaning: "艺术", example: "I like to study art. 我喜欢学习艺术。", category: "english", grade: "三年级下", unit: "第四单元", subcategory: "culture", isWritable: true },
  { id: "3B-4-16", term: "paint", pronunciation: "/peɪnt/", meaning: "绘画", example: "I can paint pictures. 我会画画。", category: "english", grade: "三年级下", unit: "第四单元", subcategory: "culture", isWritable: true },
  { id: "3B-4-17", term: "write", pronunciation: "/raɪt/", meaning: "写", example: "I can write stories. 我会写故事。", category: "english", grade: "三年级下", unit: "第四单元", subcategory: "culture", isWritable: true },
  { id: "3B-4-18", term: "draw", pronunciation: "/drɔː/", meaning: "画", example: "I can draw pictures. 我会画画。", category: "english", grade: "三年级下", unit: "第四单元", subcategory: "culture", isWritable: true }
];